from __future__ import annotations

from dataclasses import asdict, dataclass


GRAZ_OFFICES_URL = "https://www.graz.at/cms/beitrag/10019383/7743948/Aemter_und_Politik.html"
GRAZ_PHONEBOOK_URL = "https://www.graz.at/cms/ziel/7536192/"
GRAZ_APPOINTMENTS_URL = "https://www.graz.at/termine"
GRAZ_CONTACT_FORM_URL = "https://www.graz.at/cms/beitrag/10303721/8425359/"
GRAZ_DIGITAL_CITY_URL = "https://www.digitalestadt.graz.at/"
GRAZ_WEBSITE_LICENSE = "öffentliche Webseite, keine OGD-Lizenz gefunden"
GRAZ_WEBSITE_REUSE = (
    "Im Open-Source-Projekt werden nur kurze, faktische Servicehinweise und Links geführt. "
    "Aktuelle Öffnungszeiten, Zuständigkeiten und Formulare bleiben auf den offiziellen Seiten."
)


@dataclass(frozen=True)
class CivicService:
    name: str
    category: str
    address: str
    lat: float
    lon: float
    description: str
    services: list[str]
    phone: str = ""
    email: str = ""
    website: str = ""
    appointments_url: str = GRAZ_APPOINTMENTS_URL
    source: str = "Stadt Graz"
    source_url: str = GRAZ_OFFICES_URL
    license: str = GRAZ_WEBSITE_LICENSE
    reuse: str = GRAZ_WEBSITE_REUSE


def load_civic_services() -> tuple[list[dict], dict]:
    services = [asdict(service) for service in CIVIC_SERVICES]
    return services, civic_service_summary(records=len(services))


def civic_service_summary(records: int | None = None) -> dict:
    return {
        "directory_url": GRAZ_OFFICES_URL,
        "phonebook_url": GRAZ_PHONEBOOK_URL,
        "appointments_url": GRAZ_APPOINTMENTS_URL,
        "contact_form_url": GRAZ_CONTACT_FORM_URL,
        "digital_city_url": GRAZ_DIGITAL_CITY_URL,
        "license": GRAZ_WEBSITE_LICENSE,
        "attribution": "Stadt Graz",
        "records": records if records is not None else len(CIVIC_SERVICES),
        "reuse": GRAZ_WEBSITE_REUSE,
    }


CIVIC_SERVICES = [
    CivicService(
        name="Bürger:innenservice / Kontaktformular",
        category="Bürgerservice",
        address="Hauptplatz 1, 8010 Graz",
        lat=47.0707,
        lon=15.4386,
        description="Zentrale erste Anlaufstelle für Anregungen und Beschwerden an die Stadtverwaltung.",
        services=["Kontaktformular", "Anliegen an die Stadtverwaltung", "Weiterleitung an zuständige Stellen"],
        website=GRAZ_CONTACT_FORM_URL,
        source_url=GRAZ_CONTACT_FORM_URL,
    ),
    CivicService(
        name="Digitales Amt Graz",
        category="Bürgerservice",
        address="Hauptplatz 1, 8010 Graz",
        lat=47.0707,
        lon=15.4386,
        description="Digitale Abwicklung von Behördenwegen und Online-Services der Stadt Graz.",
        services=["Online-Amtswege", "Formulare", "Termin- und Serviceeinstieg"],
        website=GRAZ_DIGITAL_CITY_URL,
        source="digitalestadt.graz.at",
        source_url=GRAZ_DIGITAL_CITY_URL,
    ),
    CivicService(
        name="Amt der Bürgermeisterin",
        category="Stadtregierung & Verwaltung",
        address="Hauptplatz 1, 8010 Graz",
        lat=47.0707,
        lon=15.4386,
        description="Politisch-administrative Anlaufstelle im Bereich der Bürgermeisterin; Detailzuständigkeiten offiziell prüfen.",
        services=["Bürgermeisterin", "Stadtregierung", "Amtskontakt"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Magistratsdirektion",
        category="Stadtregierung & Verwaltung",
        address="Hauptplatz 1, 8010 Graz",
        lat=47.0707,
        lon=15.4386,
        description="Zentrale Verwaltungskoordination des Magistrats; Detailzuständigkeiten offiziell prüfen.",
        services=["Magistrat", "Verwaltungskoordination", "Amtsorganisation"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Präsidialabteilung",
        category="Stadtregierung & Verwaltung",
        address="Hauptplatz 1, 8010 Graz",
        lat=47.0707,
        lon=15.4386,
        description="Verwaltungsbereich für zentrale präsidiale Aufgaben; Detailzuständigkeiten offiziell prüfen.",
        services=["Präsidialangelegenheiten", "Sitzungen", "Verwaltung"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Kommunikation",
        category="Stadtregierung & Verwaltung",
        address="Hauptplatz 1, 8010 Graz",
        lat=47.0707,
        lon=15.4386,
        description="Kommunikations- und Informationsbereich der Stadt Graz.",
        services=["Presse", "Kommunikation", "Information"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Kontrollamt",
        category="Kontrolle & Recht",
        address="Hauptplatz 1, 8010 Graz",
        lat=47.0707,
        lon=15.4386,
        description="Kontroll- und Prüfbereich der Stadt Graz; Berichte und Zuständigkeiten offiziell prüfen.",
        services=["Kontrolle", "Prüfung", "Berichte"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Bürger:innenamt",
        category="Meldewesen & Dokumente",
        address="Schmiedgasse 26, 8010 Graz",
        lat=47.0688,
        lon=15.4397,
        description="Anlaufstelle für Meldewesen, Dokumente und häufige persönliche Behördenwege.",
        services=["Meldewesen", "Reisedokumente", "Passamt", "Urkunden", "Wahlen/Volksbegehren"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Passservice / Reisedokumente",
        category="Meldewesen & Dokumente",
        address="Schmiedgasse 26, 8010 Graz",
        lat=47.0688,
        lon=15.4397,
        description="Orientierungspunkt für Reisepass, Personalausweis und Reisedokumente; Termine und Detailvoraussetzungen offiziell prüfen.",
        services=["Reisepass", "Personalausweis", "Passamt", "Reisedokumente", "Terminvereinbarung"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Bau- und Anlagenbehörde",
        category="Bauen & Wohnen",
        address="Europaplatz 20, 8020 Graz",
        lat=47.0723,
        lon=15.4178,
        description="Behörde für Bau- und Anlagenverfahren im Stadtgebiet.",
        services=["Bauverfahren", "Anlagenverfahren", "Parteienverkehr nach Termin"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Stadtbaudirektion",
        category="Bauen & Wohnen",
        address="Europaplatz 20, 8020 Graz",
        lat=47.0723,
        lon=15.4178,
        description="Koordination städtischer Bau- und Infrastrukturthemen; Detailzuständigkeiten offiziell prüfen.",
        services=["Stadtbau", "Infrastruktur", "Projektkoordination"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Stadtplanungsamt",
        category="Bauen & Wohnen",
        address="Europaplatz 20, 8020 Graz",
        lat=47.0723,
        lon=15.4178,
        description="Zuständig für Stadtplanung, Flächenwidmung und städtebauliche Grundlagen.",
        services=["Stadtplanung", "Flächenwidmung", "Bebauungsplanung"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Stadtvermessungsamt",
        category="Bauen & Wohnen",
        address="Europaplatz 20, 8020 Graz",
        lat=47.0723,
        lon=15.4178,
        description="Fachstelle für Vermessung, Geodaten und städtische Planungsgrundlagen.",
        services=["Vermessung", "Geodaten", "Stadtplan"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Immobilien",
        category="Bauen & Wohnen",
        address="Schillerplatz 4, 8010 Graz",
        lat=47.0733,
        lon=15.4523,
        description="Städtischer Immobilienbereich; konkrete Angebote und Zuständigkeiten offiziell prüfen.",
        services=["Immobilien", "Liegenschaften", "Städtische Objekte"],
        website="https://www.immobilien.graz.at/",
        source="Immobilien Graz",
        source_url="https://www.immobilien.graz.at/",
    ),
    CivicService(
        name="Wohnungsangelegenheiten",
        category="Bauen & Wohnen",
        address="Schillerplatz 4, 8010 Graz",
        lat=47.0733,
        lon=15.4523,
        description="Anlaufstelle für städtische Wohnungsangelegenheiten und Wohnservice.",
        services=["Gemeindewohnungen", "Wohnberatung", "Wohnunterstützung weiterführend prüfen"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Wohnen Graz",
        category="Bauen & Wohnen",
        address="Schillerplatz 4, 8010 Graz",
        lat=47.0733,
        lon=15.4523,
        description="Eigenbetrieb rund um städtisches Wohnen; Detailangebote offiziell prüfen.",
        services=["Wohnen", "Gemeindewohnungen", "Wohnservice"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Sozialamt",
        category="Soziales",
        address="Schmiedgasse 26, 8010 Graz",
        lat=47.0688,
        lon=15.4397,
        description="Zuständig für soziale Unterstützung und Sozialleistungen der Stadt.",
        services=["Sozialleistungen", "Beratung", "Unterstützung in Notlagen"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Jugend und Familie",
        category="Familie & Bildung",
        address="Kaiserfeldgasse 25, 8010 Graz",
        lat=47.0675,
        lon=15.4397,
        description="Service- und Fachstelle für Kinder, Jugendliche und Familien.",
        services=["Familienservice", "Kinder- und Jugendhilfe", "Beratung"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Bildung und Integration",
        category="Familie & Bildung",
        address="Keesgasse 6, 8010 Graz",
        lat=47.0679,
        lon=15.4428,
        description="Zuständig für Bildungsthemen, Kinderbetreuung und Integration.",
        services=["Bildung", "Kinderbetreuung", "Integration"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Gesundheitsamt",
        category="Gesundheit",
        address="Schmiedgasse 26, 8010 Graz",
        lat=47.0688,
        lon=15.4397,
        description="Gesundheitsbehördliche Aufgaben und öffentliche Gesundheitsservices.",
        services=["Gesundheitsbehörde", "Beratung", "Amtsärztliche Themen"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Geriatrische Gesundheitszentren GGZ",
        category="Gesundheit",
        address="Albert-Schweitzer-Gasse 36, 8020 Graz",
        lat=47.0652,
        lon=15.4224,
        description="Gesundheits- und Pflegeeinrichtungen der Stadt Graz.",
        services=["Pflege", "Geriatrie", "Gesundheitsversorgung"],
        website="https://ggz.graz.at/",
        source="GGZ Graz",
        source_url="https://ggz.graz.at/",
    ),
    CivicService(
        name="Krankenfürsorgeanstalt KFA",
        category="Gesundheit",
        address="Hauptplatz 1, 8010 Graz",
        lat=47.0707,
        lon=15.4386,
        description="Krankenfürsorge der Stadt Graz; Anspruch und Leistungen offiziell prüfen.",
        services=["Krankenfürsorge", "Versicherung", "Gesundheitsleistungen"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Straßenamt",
        category="Verkehr & Öffentlicher Raum",
        address="Europaplatz 20, 8020 Graz",
        lat=47.0723,
        lon=15.4178,
        description="Zuständig für Straßen, temporäre Nutzungen und Baustellenthemen im öffentlichen Raum.",
        services=["Straßenverwaltung", "Baustellen", "Sondernutzungen"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Verkehrsplanung",
        category="Verkehr & Öffentlicher Raum",
        address="Europaplatz 20, 8020 Graz",
        lat=47.0723,
        lon=15.4178,
        description="Fachstelle für Verkehrsplanung, Mobilität und Verkehrskonzepte.",
        services=["Verkehrsplanung", "Mobilitätsplanung", "Rad- und Fußverkehr"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Grazer Parkraum- und Sicherheitsservice GPS",
        category="Verkehr & Öffentlicher Raum",
        address="Jakominigürtel 20, 8010 Graz",
        lat=47.0608,
        lon=15.4496,
        description="Service rund um Parkraumüberwachung und kommunale Sicherheitsdienstleistungen.",
        services=["Parkraum", "Sicherheitsservice", "Kontrollen"],
        website="https://www.gps.graz.at/",
        source="GPS Graz",
        source_url="https://www.gps.graz.at/",
    ),
    CivicService(
        name="Umweltamt",
        category="Umwelt",
        address="Schmiedgasse 26, 8010 Graz",
        lat=47.0688,
        lon=15.4397,
        description="Fachstelle für Umwelt, Lärm, Luft und Klima im Zuständigkeitsbereich der Stadt.",
        services=["Umwelt", "Lärm/Luft", "Förderungen und Beratung prüfen"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Grünraum und Gewässer",
        category="Umwelt",
        address="Europaplatz 20, 8020 Graz",
        lat=47.0723,
        lon=15.4178,
        description="Zuständig für städtischen Grünraum, Bäume, Parks und Gewässerthemen.",
        services=["Parks", "Bäume", "Gewässer"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Finanzdirektion",
        category="Abgaben & Finanzen",
        address="Schmiedgasse 26, 8010 Graz",
        lat=47.0688,
        lon=15.4397,
        description="Finanzverwaltung der Stadt Graz; Detailzuständigkeiten offiziell prüfen.",
        services=["Finanzen", "Budget", "Finanzverwaltung"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Gemeindeabgaben",
        category="Abgaben & Finanzen",
        address="Schmiedgasse 26, 8010 Graz",
        lat=47.0688,
        lon=15.4397,
        description="Anlaufstelle für kommunale Abgaben und Gebühren.",
        services=["Gemeindeabgaben", "Gebühren", "Bescheide"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Rechnungswesen",
        category="Abgaben & Finanzen",
        address="Schmiedgasse 26, 8010 Graz",
        lat=47.0688,
        lon=15.4397,
        description="Rechnungswesen der Stadt Graz; Detailzuständigkeiten offiziell prüfen.",
        services=["Rechnungswesen", "Zahlungen", "Finanzverwaltung"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Personalamt",
        category="Stadtregierung & Verwaltung",
        address="Hauptplatz 1, 8010 Graz",
        lat=47.0707,
        lon=15.4386,
        description="Personalbereich des Magistrats; Jobs und Kontaktwege offiziell prüfen.",
        services=["Personal", "Jobs", "Magistrat"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Kulturamt",
        category="Kultur & Sport",
        address="Hauptplatz 1, 8010 Graz",
        lat=47.0707,
        lon=15.4386,
        description="Fachstelle für Kulturangelegenheiten und Kulturförderung.",
        services=["Kultur", "Kulturförderung", "Veranstaltungen"],
        website="https://www.kultur.graz.at/",
        source="Kultur Graz",
        source_url="https://www.kultur.graz.at/",
    ),
    CivicService(
        name="Sportamt",
        category="Kultur & Sport",
        address="Hauptplatz 1, 8010 Graz",
        lat=47.0707,
        lon=15.4386,
        description="Anlaufstelle für Sportförderung, Sportstätten und Sportangelegenheiten.",
        services=["Sport", "Sportförderung", "Sportstätten"],
        website=GRAZ_OFFICES_URL,
    ),
    CivicService(
        name="Wirtschaft",
        category="Wirtschaft",
        address="Schmiedgasse 26, 8010 Graz",
        lat=47.0688,
        lon=15.4397,
        description="Service für Wirtschaft, Betriebsansiedlung und wirtschaftsbezogene Anliegen.",
        services=["Wirtschaftsservice", "Betriebe", "Förderinformationen prüfen"],
        website="https://www.wirtschaft.graz.at/",
        source="Wirtschaft Graz",
        source_url="https://www.wirtschaft.graz.at/",
    ),
    CivicService(
        name="Feuerwehr Graz",
        category="Sicherheit & Notfälle",
        address="Lendplatz 15-17, 8020 Graz",
        lat=47.0739,
        lon=15.4302,
        description="Berufsfeuerwehr und Brandschutzinformationen der Stadt Graz.",
        services=["Notfall/Feuerwehr", "Brandschutz", "Sicherheitshinweise"],
        website="https://feuerwehr.graz.at/",
        source="Feuerwehr Graz",
        source_url="https://feuerwehr.graz.at/",
    ),
    CivicService(
        name="Holding Graz Service",
        category="Kommunale Services",
        address="Andreas-Hofer-Platz 15, 8010 Graz",
        lat=47.0697,
        lon=15.4372,
        description="Kommunale Dienstleistungen wie Öffentlicher Verkehr, Abfall, Wasser und Infrastruktur werden bei der Holding Graz geprüft.",
        services=["Öffentlicher Verkehr", "Abfall", "Wasser/Kanal", "Kundenservice"],
        website="https://www.holding-graz.at/",
        source="Holding Graz",
        source_url="https://www.holding-graz.at/",
        license="nur verlinkt; aktuelle Details offiziell prüfen",
        reuse="Im Viewer nur als Service-Link und kurzer Orientierungshinweis geführt.",
    ),
]
